//! Which items the game can still produce.
//!
//! An item token's supply grows only when a player obtains the item in game and
//! bridges it out. So an item that nothing in the world produces has a supply
//! fixed at whatever was seeded on chain — and that, not the price, is what
//! makes something worth accumulating in an economy whose currency is minted by
//! anyone with a nature rune.
//!
//! The table is generated by `gamebot/tools/build-item-sources.ts`, which
//! searches the game's own content scripts for each item's debugname across four
//! kinds of source (drop tables, shop stock lists, skill scripts, quest rewards)
//! plus the map ground spawns. 62 of the 1,374 registry items match none of them.
//!
//! This is a heuristic and is documented as one: a name could be produced by a
//! script that spells it differently. Every signal is kept rather than just the
//! verdict, so a caller can weigh them, and live on-chain supply above the seed
//! is treated as evidence that beats the heuristic outright.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::{Deserialize, Serialize};

/// How an item can enter a player's inventory.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ItemSources {
    /// Named in an NPC drop table.
    pub drop: bool,
    /// Stocked by a shop.
    pub shop: bool,
    /// Produced by a skill: fishing, smithing, crafting, and so on.
    pub skill: bool,
    /// Given as a quest reward.
    pub quest: bool,
    /// Spawns on the ground somewhere in the world.
    pub spawn: bool,
    /// None of the above — nothing in the game produces this item.
    pub capped: bool,
}

impl ItemSources {
    /// Whether any route into the game exists.
    pub fn obtainable(&self) -> bool {
        self.drop || self.shop || self.skill || self.quest || self.spawn
    }

    /// A short description of where the item comes from.
    pub fn describe(&self) -> String {
        if self.capped {
            return "no in-game source".to_string();
        }
        let mut parts = Vec::new();
        for (flag, label) in [
            (self.drop, "drops"),
            (self.shop, "shops"),
            (self.skill, "skills"),
            (self.quest, "quests"),
            (self.spawn, "ground spawns"),
        ] {
            if flag {
                parts.push(label);
            }
        }
        parts.join(", ")
    }
}

/// How many units of each item the genesis seeding put into its pool.
///
/// `chain/runner/lib/common.ts`: `SEED_PER_ITEM = 100n`, for every item.
pub const POOL_SEED_UNITS: u64 = 100;

static TABLE: OnceLock<HashMap<String, ItemSources>> = OnceLock::new();

/// The generated source table, keyed by registry debugname.
pub fn table() -> &'static HashMap<String, ItemSources> {
    TABLE.get_or_init(|| {
        serde_json::from_str(include_str!("../data/item_sources.json"))
            .expect("item_sources.json is generated and must parse")
    })
}

/// Look up one item. Unknown items are reported as obtainable, because an item
/// the table has never heard of is not evidence of scarcity.
pub fn sources_for(key: &str) -> ItemSources {
    table().get(key).copied().unwrap_or(ItemSources {
        drop: true,
        ..Default::default()
    })
}

/// Every item with no in-game source.
pub fn capped_items() -> Vec<&'static str> {
    let mut keys: Vec<&str> = table()
        .iter()
        .filter(|(_, sources)| sources.capped)
        .map(|(key, _)| key.as_str())
        .collect();
    keys.sort_unstable();
    keys
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_covers_the_registry() {
        assert_eq!(table().len(), 1_374);
        assert_eq!(capped_items().len(), 62);
    }

    #[test]
    fn the_discontinued_rares_have_no_in_game_source() {
        // Party hats come only from pulling a christmas cracker, and crackers
        // have no drop table, shop or ground spawn — so both are capped.
        for rare in [
            "red_partyhat",
            "blue_partyhat",
            "purple_partyhat",
            "santa_hat",
            "halloweenmask_red",
            "christmas_cracker",
        ] {
            let sources = sources_for(rare);
            assert!(sources.capped, "{rare} should be capped: {sources:?}");
            assert!(!sources.obtainable());
            assert_eq!(sources.describe(), "no in-game source");
        }
    }

    #[test]
    fn farmable_items_are_not_mistaken_for_scarce() {
        let lobster = sources_for("lobster");
        assert!(!lobster.capped);
        assert!(lobster.skill, "lobsters are fished");
        assert!(lobster.describe().contains("skills"));

        let rune = sources_for("naturerune");
        assert!(!rune.capped);
        assert!(rune.shop, "the Wizards' Guild stocks them");
    }

    #[test]
    fn an_unknown_item_is_not_treated_as_scarce() {
        let unknown = sources_for("not_a_real_item");
        assert!(!unknown.capped);
        assert!(unknown.obtainable());
    }
}
